### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Anoaxx** [Terrails/StatsKeeper#34] opened 2021-08-26 18:39 UTC
I have some suggestions if you like. 

1. This should be one option:
```
		"keep_experience": true,
		"drop_experience": false
```

2. This should be disable by default:
```
	"health": {
		"enabled": false,
```

3. Please explain this better because i get it after 10 min that is option to not adding/removing health if your health is between this values but i don't get it at first moment. If im still wrong then tell me. 
```
			"thresholds": [
				-8,
				16
```

4. Add more items here like e.g. Enchanted Golden Apple or Dragon Egg etc. And add option to not "eat" this items unintentionally. 
```
			"regenerative_items": [
				"minecraft:nether_star = 1"
```

5. And Last but not least:

Add mod menu config compatibility. Seriously man if you can't configure this mod in game and someone just throw this mod into mods folder, loads its world and see 3 hearts of health and cant change it in game just gonna throw this mod away to trash. Just i do but i throw it back because YOUR MOD NOT RESTORING HELTH to original state if deleted. ;-; And Yes, this issue made me to write all of this. Have a nice day!

**Comment by DaveHyral** [comment] 2021-09-17 07:52
Is there any plans to make it possible to expand max HP past 1024? I play EXTREMELY modded MC which puts stupidly strong mobs and mob gangs in the game which actually would warrant HP limits past the 1024 limit.

**Comment by Anoaxx** [comment] 2021-09-18 20:39
> Is there any plans to make it possible to expand max HP past 1024? I play EXTREMELY modded MC which puts stupidly strong mobs and mob gangs in the game which actually would warrant HP limits past the 1024 limit.

Open new issue for this.

**Comment by Terrails** [comment] 2021-09-18 20:54
Sorry for no updates on this for some while now, but I've been really busy lately and have also been changing the layout of my modding workspace (using Architectury for easier dev with fabric and forge). I'll hopefully be implementing these features by the end of this week.



> 
> 
> Is there any plans to make it possible to expand max HP past 1024? I play EXTREMELY modded MC which puts stupidly strong mobs and mob gangs in the game which actually would warrant HP limits past the 1024 limit.

This is kind of complicated as I would need to write a coremod (mixin) to do this on forge. I haven't yet looked into mixin support that was added in the latest version of forge. I could look into implementing it on fabric for now.

**Comment by DaveHyral** [comment] 2021-09-19 18:16
Oh i wasn't asking about Forge. :3 I'd never support a mod platform owned
by an absolute waste of oxygen who belittles anybody who outdoes him. The
things LexManos has said and done about JellySquid3 is.. revolting.

**Comment by Terrails** [comment] 2021-09-25 12:47
> 
> 
> Is there any plans to make it possible to expand max HP past 1024? I play EXTREMELY modded MC which puts stupidly strong mobs and mob gangs in the game which actually would warrant HP limits past the 1024 limit.

Seems like AttributeFix on Forge and the port on Fabric do this, the issue is that Stats Keepr was just limiting the config values to 1024, I'll have the config max value use the actual max value that the attribute returns.

> 
> 
> Sorry for no updates on this for some while now, but I've been really busy lately and have also been changing the layout of my modding workspace (using Architectury for easier dev with fabric and forge). I'll hopefully be implementing these features by the end of next week.
> 
> > Is there any plans to make it possible to expand max HP past 1024? I play EXTREMELY modded MC which puts stupidly strong mobs and mob gangs in the game which actually would warrant HP limits past the 1024 limit.
> 
> This is kind of complicated as I would need to write a coremod (mixin) to do this on forge. I haven't yet looked into mixin support that was added in the latest version of forge. I could look into implementing it on fabric for now.

I am basically done with fixing and implemeting features and I'll have a release ready by the end of the day. There's still no config GUI unfortunately, but the config values load themselves on server start, so closing and opening a client world will load the updated values in the config file. 
I still have to see how exactly I'll implement ingame config, since I want to unify forge and fabric code as much as possible, so I might have to write a layer on top of the config systems from both modloaders that turns the values into valid GUI elements. Switching to ClothConfig is also an option due to it already being available on both modloaders, so that's what I'm probably going to do. It will add a dependency to the mod and I'll have to change the config system I use on fabric due to fiber2cloth not being maintained that much anymore.

**Closed** 2023-06-11 00:19 UTC
